CREATE TABLE `oneqsite` (
	`SiCode` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
	`SiName` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
	`SiSeq` INT(11) NULL DEFAULT NULL,
	`GuCode` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
	`GuName` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
	`GuSeq` INT(11) NULL DEFAULT NULL,
	`DongCode` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
	`DongName` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
	`DongSeq` INT(11) NULL DEFAULT NULL
)
COLLATE='utf8mb3_general_ci'
ENGINE=InnoDB
;
